[project]
name = "beam_engine"
version = "0.1.0"
dependencies = [
    "torch==2.9.1",
    "flashinfer-python",
    "transformers==4.57.3",
    "ninja",
]

[tool.uv]
packages = ["beam_engine"]
no-build-isolation-package = ["torch"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"